/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class utils_JniUtil */

#ifndef _Included_utils_JniUtil
#define _Included_utils_JniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     utils_JniUtil
 * Method:    getStringFromNDK
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_utils_JniUtil_getStringFromNDK
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
